### ISSUE TITLE
没办法取色

### ISSUE THREAD

**Issue by zhuliminl** [guowenfh/chrome-color-picker#1]
chrome 版本 Version 76.0.3809.100 (Official Build) (64-bit)

**Comment by zhuliminl** [comment]
被忽视了哈哈哈哈

**Comment by guowenfh** [comment]
@zhuliminl 请问是第一次使用的时候无法取色吗？（在第一次的时候无法去色，已经确定了问题）
如果是其他情况，右键菜单以及顶部按钮都不行的话，请麻烦你提供一下更详细的信息

**Comment by zhuliminl** [comment]
> @zhuliminl 请问是第一次使用的时候无法取色吗？（在第一次的时候无法去色，已经确定了问题）
> 如果是其他情况，右键菜单以及顶部按钮都不行的话，请麻烦你提供一下更详细的信息

确实是第一次。后来就没问题了。为什么第一次无法使用哈

**Comment by zhuliminl** [comment]
确实是第一次无法取色哈哈。以后都没问题了。为什么第一次无法使用哈

**Comment by guowenfh** [comment]
因为在第一次安装的时候没有注入到页面的事件监听器。。必须要页面刷新才行 - -. 还在想咋办，应该是有办法的

**Comment by zhuliminl** [comment]
> 因为在第一次安装的时候没有注入到页面的事件监听器。。必须要页面刷新才行 - -. 还在想咋办，应该是有办法的

原来如此。哈哈。我15年的时候，正准备学前端，很想转行。然后，那个时候看到你在知乎上提了一个问题，当时贺师俊、顾灵还有谁忘了他们的名字了，都很称赞你。真的好羡慕你哈。你写的博客，我几乎每篇都看了。对我帮助很大😄
